#pragma once

namespace AnimationTool
{
	enum PASSID_VTX { VTX_DEFAULT, VTX_END };
	enum PASSID_VTXTEX { VTXTEX_DEFAULT, VTXTEX_ALPHA, VTXTEX_END };
	enum PASSID_VTXNORTEX { VTXNORTEX_DEFAULT, VTXNORTEX_END };
	enum PASSID_VTXMESH { VTXMESH_DEFALUT, VTXMESH_NONCULL, VTXMESH_END };
	enum PASSID_VTXANIMMESH { VTXANIMMESH_DEFAULT, VTXANIMMESH_NWORLD, VTXANIMMESH_SHADOW, VTXANIMMESH_END };
	enum PASSID_TRAIL { TRAIL_DEFAULT, TRAIL_END };
}