#pragma once

namespace Tool
{
	enum LEVELID { LEVEL_STATIC, LEVEL_EDIT, LEVEL_LOADING, LEVEL_END };
	enum COLLID { COLL_END };

	enum CREATUREID {
		CHARACTER_TRAVELER,
		CHARACTER_AMBOR, CHARACTER_BARBARA, CHARACTER_DILUC, CHARACTER_GANYU,
		CHARACTER_HUTAO, CHARACTER_NAHIDA, CHARACTER_YAE, CHARACTER_ZHONGLI,
		CREATURE_END
	};

	enum FSM_STATE {
		FSM_IDLE, FSM_WALK, FSM_SPLINT, FSM_DASH,
		FSM_END
	};

	enum PASSID_VTX { VTX_DEFAULT, VTX_END };
	enum PASSID_VTXTEX { VTXTEX_DEFAULT, VTXTEX_ALPHA, VTXTEX_END };
	enum PASSID_VTXNORTEX { VTXNORTEX_DEFAULT, VTXNORTEX_END };
	enum PASSID_VTXMESH { VTXMESH_DEFALUT, VTXMESH_NONCULL, VTXMESH_END };
	enum PASSID_VTXANIMMESH { VTXANIMMESH_DEFAULT, VTXANIMMESH_NWORLD, VTXANIMMESH_SHADOW, VTXANIMMESH_END };

	enum OBJECT_TAG
	{
		OBJECT_MONDBASE,
		OBJECT_WINDMILL,
		OBJECT_CHURCH,
		OBJECT_VENTISTATUE,
		OBJECT_MOND_GATE,
		OBJECT_SQUARE,
		OBJECT_WALL_1,
		OBJECT_WALL_2,
		OBJECT_TOWER_1,
		OBJECT_TOWER_2,
		OBJECT_GUILD,
		OBJECT_KNIGHT,
		OBJECT_ANGELSHARE,
		OBJECT_CAT_TAIL,
		OBJECT_MAJORIE_STORE,
		OBJECT_SARA_FOOD_STORE,
		OBJECT_VARIETY_STORE,
		OBJECT_WAGNER_STORE,
		OBJECT_STORE_01,
		OBJECT_STORE_02,
		OBJECT_STORE_03,
		OBJECT_STORE_04,
		OBJECT_STORE_05,
		OBJECT_STORE_07,
		OBJECT_STORE_08,
		OBJECT_STORE_11,
		OBJECT_STORE_12,
		OBJECT_STORE_13,
		OBJECT_STORE_16,
		OBJECT_STORE_21,
		OBJECT_STORE_22,
		OBJECT_STORE_24,
		OBJECT_STORE_25,
		OBJECT_STORE_41,
		OBJECT_HOUSE_BABALA,
		OBJECT_HOTEL_GOETHE,
		OBJECT_HOUSE_01,
		OBJECT_HOUSE_02,
		OBJECT_HOUSE_03,
		OBJECT_HOUSE_04,
		OBJECT_HOUSE_05,
		OBJECT_HOUSE_06,
		OBJECT_HOUSE_07,
		OBJECT_HOUSE_08,
		OBJECT_HOUSE_09,
		OBJECT_HOUSE_10,
		OBJECT_END
	};

	enum WORLD_ELEMENT_TYPE
	{
		WORLD_ELEMENT_NONE,
		WORLD_ELEMENT_INTERACTION,
		WORLD_ELEMENT_END
	};
}